spring.application.name=RestroRealm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/restrorealm
spring.datasource.username = root
spring.datasource.password = Sai@2206
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
server.port=8080
jwt.secret=+oMMuuHBrCu7bcaTyMyCgNBwn/8FSBL57zxQ0gYYkWv91Dw41LOs2dK340rPX/5vdcIm27ZnbZcvBIUPh12K3w==
# Randomly generated key
jwt.expiration=3600000
