spring.application.name=RestroRealm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/restrorealm
spring.datasource.username = root
spring.datasource.password = Sai@2206
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
server.port=8080
jwt.secret=ab40e11035416830e5a21b0e14da7338a70a18e0b0129dc5e2e8b79e729f632b
# Plain Text - RestroRealmEncryptionKeyIsKeptSecret
# Secret Key - Nothing
# Hash type - SHA256(Hex)
jwt.expiration=3600000
